name: Pre release on tag
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - run: make test

  release:
    strategy:
      matrix:
        os: ["linux", "darwin"]
        arch: ["amd64"]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2
      - id: release
        run: |
          echo ::set-output name=name::"${GITHUB_REF#refs/tags/v}"
          echo ::set-output name=date::"$(date +'%F')"
      - name: build release file
        env:
           GOOS: ${{ matrix.os }}
           GOARCH: ${{ matrix.arch }}
           RELEASE_NAME: ${{ steps.release.outputs.name }}
        run: |
          go build -o cmd/tf-module-update/tf-module-update-${RELEASE_NAME}.${GOOS}-${GOARCH} ./cmd/tf-module-update/
          zip -j cmd/tf-module-update/tf-module-update-${RELEASE_NAME}.${GOOS}-${GOARCH}.zip cmd/tf-module-update/tf-module-update-${RELEASE_NAME}.${GOOS}-${GOARCH}
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ${{ steps.release.outputs.name }} / ${{ steps.release.outputs.date }}
          fail_on_unmatched_files: true
          files: |
            cmd/tf-module-update/tf-module-update-${{ steps.release.outputs.name }}.*
