name: Pre release on tag
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: ["linux", "darwin"]
        arch: ["amd64"]
    steps:
      - uses: actions/checkout@v2
      - run: make test

  release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: ["linux", "darwin"]
        arch: ["amd64"]
    steps:
      - uses: actions/checkout@v2
      - id: release
        run: |
          echo ::set-output name=name::"${GITHUB_REF#refs/tags/v}"
          echo ::set-output name=date::"$(date +'%F')"
      - run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o cmd/tf-module-update/tf-module-update-${{ steps.release.outputs.name }}.${{ matrix.os }}-${{ matrix.arch }} ./cmd/tf-module-update/
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ${{ steps.release.outputs.name }} / ${{ steps.release.outputs.date }}
          fail_on_unmatched_files: true
          files: |
            cmd/tf-module-update/tf-module-update-${{ steps.release.outputs.name }}.*
